name: MLOPS CI/CD Pipeline

on:
  push:
    branches:
      - feature/m1-cicd-pipeline
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn pandas dvc

    - name: Set up temporary storage
      run: mkdir -p ./tmp/dvc-storage

    - name: Configure DVC remote
      run: dvc remote add -d temp_remote ./tmp/dvc-storage

    - name: Pull dataset using DVC
      run: dvc pull

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run tests
      run: |
        pytest