name: MLOPS CI/CD Pipeline

on:
  push:
    branches:
      - feature/m1-cicd-pipeline
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DVC_GDRIVE_CREDENTIALS: service-account-key.json
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn pandas
        pip install "dvc[gdrive]"

    - name: Configure Google Drive credentials
      run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}" > service-account-key.json

    - name: Lint with flake8
      run: |
        flake8 .

    - name: DVC INIT
      run: |
        dvc init

    - name: Clear dvc config cache
      run: |
        rm -rf .dvc/config
        rm -rf .dvc/.cache

    - name: Set DVC remote
      run: |
        dvc remote add -d mlops-dataset gdrive://1z2-YIszgPRvkdtSjBSqbU6BACfzSYrgn

    - name: Check DVC remote list
      run: |
        dvc remote list

    - name: Reset auth method
      run: |
        dvc config --global remote.mlops-dataset.auth ""

    - name: Pull DVC data from Google Drive
      run: |
        dvc pull -v

    - name: Clean up service account key
      run: |
        rm -f service-account-key.json

    - name: Run tests
      run: |
        pytest