name: MLOPS CI/CD Pipeline

on:
  push:
    branches:
      - feature/m1-cicd-pipeline
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn pandas

    - name: Lint with flake8
      run: |
        flake8 .
    - name: Install DVC with Google Drive support
      run: |
          pip install "dvc[gdrive]"
    - name: Configure Google Drive credentials
      run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}" > service-account-key.json
          export DVC_GDRIVE_CREDENTIALS=service-account-key.json
    - name: DVC INIT
      run: |
        dvc init
    - name: Set DVC remote
      run: |
        dvc remote add -d mlops-dataset gdrive://1z2-YIszgPRvkdtSjBSqbU6BACfzSYrgn
    - name: Reset auth method
      run: |
        dvc remote modify mlops-dataset --local --unset auth
    - name: DVC credentials modify
      run: |
        dvc remote modify mlops-dataset gdrive_credentials_file ./service-account-key.json
    - name: Pull DVC data from Google Drive
      run: dvc pull
    - name: Run tests
      run: |
        pytest