name: MLOPS CI/CD Pipeline

on:
  push:
    branches:
      - feature/m1-cicd-pipeline
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run tests
      run: |
        pytest