name: MLOPS CI/CD Pipeline

on:
  push:
    branches:
      - feature/m1-cicd-pipeline
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DVC_GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn pandas
        pip install "dvc[gdrive]"

    - name: Lint with flake8
      run: |
        flake8 .

    - name: DVC INIT
      run: |
        dvc init

    - name: Set DVC remote
      run: |
        dvc remote add -d mlops-dataset gdrive://1z2-YIszgPRvkdtSjBSqbU6BACfzSYrgn

    - name: Export env variable
      run: |
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}" > service-account-key.json
        export DVC_GDRIVE_CREDENTIALS=service-account-key.json

    - name: Verify service account key
      run: cat service-account-key.json

    - name: Verify DVC_GDRIVE_CREDENTIALS variable
      run: echo $DVC_GDRIVE_CREDENTIALS

    - name: Check service account key file size
      run: |
        ls -lh service-account-key.json
        wc -l service-account-key.json

    - name: Set DVC remote with service account authentication
      run: |
        dvc remote modify mlops-dataset gdrive_use_service_account true
        dvc remote modify mlops-dataset gdrive_service_account_json_file_path ./service-account-key.json
        dvc remote modify mlops-dataset gdrive_service_account_user_email dvc-service-account@flash-hour-449016-j7.iam.gserviceaccount.com

    - name: Check DVC remote list
      run: |
        dvc remote list

    - name: Pull DVC data from Google Drive
      run: |
        dvc pull -v

    - name: Clean up service account key
      run: |
        rm -f service-account-key.json

    - name: Run tests
      run: |
        pytest